server:
  port: 8081

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vanilla_bank_db
    username: postgres
    password: vb123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    default-schema: vanilla_bank
springdoc:
  api-docs:
    path: /api-docs
