server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/vanilla_bank_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSl=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
