CREATE TABLE IF NOT EXISTS "vanilla_bank".conta_corrente
(
    cntc_id             bigint                NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cntc_cartao_credito character varying(16) NOT NULL,
    cntc_saldo          numeric(19, 2)        NOT NULL,
    cntc_clt_id         bigint                NOT NULL,
    CONSTRAINT conta_corrente_pkey PRIMARY KEY (cntc_id),
    CONSTRAINT uc_conta_corrente_cartao_credito UNIQUE (cntc_cartao_credito),
    CONSTRAINT uc_conta_corrente_cntc_clt_id UNIQUE (cntc_clt_id),
    CONSTRAINT fk_conta_corrente_cliente_id FOREIGN KEY (cntc_clt_id)
        REFERENCES "vanilla_bank".cliente (clt_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);