CREATE TABLE IF NOT EXISTS "vanilla_bank".movimentacao
(
    mov_id                   bigint                      NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    mov_data                 timestamp without time zone NOT NULL,
    mov_numero_conta_destino bigint,
    mov_numero_conta_origem  bigint                      NOT NULL,
    mov_tipo_movimentacao    character varying(13)       NOT NULL,
    mov_valor                numeric(19, 2),
    CONSTRAINT movimentacao_pkey PRIMARY KEY (mov_id)
);